### ISSUE TITLE
spectator example: an insecure websocket connection may not be initiated from a page loaded over https

### ISSUE THREAD

**Issue by zantiu** [Rufus31415/Simple-WebXR-Unity#10]
I have problems to make the spectator example work.

Desktop:
After entering ip address of hololens the browser shows a message "an insecure websocket connection may not be initiated from a page loaded over https".
In Chrome this can be bypassed by site settings > Insecure content > Allow.
After this bypass the example works

Ipad:
Nothing happens after entering the ip address. I suspect the socket connection is also blocked but without message.

Android:
Somehow I can only load the app in Firefox, but not in Chrome because of memory limitations.
Firefox also fails with the message "SecurityError: The operation is insecure". I didn't find a way to bypass this on Firefox.

Is it possible to switch to secure websocket in the spectator example?

**Comment by zantiu** [comment]
Update: tested by serving the webpage locally an that is working, at least for Android.

**Comment by Rufus31415** [comment]
Thank you for this feedback :)
This example is a prototype. The security problem does not occur on the WebXRViewer browser on iOS.
It would be possible to work with wss:// but the security would have to be handled on the Hololens side. If you have the time and the skills, I'll take it! Otherwise, thank you for this information on how to set up browsers to make it work.

But I think the main improvement I'll have on this example is to use QRCode instead of touching the screen to synchronize the positions of the Hololens and the WebXR device. The problem with the touch is that the orientation is inaccurate.
